language: python
sudo: false
python:
- 2.7.10
- 2.7.13

addons:
  apt:
    packages:
    - ruby1.9.3
    # Install binary package for lxml to speed up build
    - python-lxml

cache:
  pip: true
  directories:
  - node_modules  # NPM packages

before_install:
# Install latest stable NodeJS version. Required for eslint.
- nvm install stable
- gem install coveralls-lcov

install:
- make dev-install

before_script:
# Install bower, eslint, eslint-config-edx-es5 and their dependencies
- make tools
- make deps-test

script:
- make quality-py
- make quality-js
- make test

after_success:
- make coveralls
notifications:
  slack:
    secure: BmwAxUvohFcruAoIjqcw35q7xbWWl7BV+ABaWO4Fxc+hC20tPNzQUjMLgzYboMtaiBLncMpiFhriv2KCQs6khKtnertZPKfhG01FP/vQ2FPYF3p5K2ZvCsfkTeSKKtohmH0rMCuuRu/Wt3ACbcX/9KMc7Lrn0knaUyqTApJm24HVCkCsnL5MDkZT3AxnuCURdYaq+BTiPWJnmyZMrRNxGH/WcperVy0T4LxYnhpg6xGnyfyip0IDXOGp77pn5LcDiqhE3ISthH170arGxWyBvwLdeTSqTN8hViGqOVe9oBy5GrdNvNsqVRN6MLONSQNOnNT8P+F1m7h7sRohvFG0ZcJK6spKA7QhUGk8Wj6Kp5hdOK/cAd786HfusdJkRLUgyW1TAj/LsUE/z5VQgxoN8GtjSLtEjiHLTW1ueGxJ48LODFjzT7MptUyvSf98EK9emVbgYoGE2d0HkXDv9hqF63n8yGc7rGMNvS0I0e9nQ+9QdPjkT4KTNpJgiRDtrFK/8/P4hmgmEYXvC1//t5H+BrVMymH2v/+jvwn56zb+RbvK8yt7wHLgtENxEECQWy6QgYXUry3AfMOsaBOpVCW/ATCotM1+lkyjb0YLTmRNuTfJx2hvUc1gxJPr1WUZur4Cz87fVWUM9k4aFD9gKeR1JOTMc71leQNAmdYVDI0ypMc=
